spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.1.242:3306/studb?useUnicode=true&characterEncoding=utf-8
    username: write
    password: write123
  redis:
      # Redis使用那个库
      database: 2
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接密码（默认为空）
      password: 123456
      # Redis服务器连接端口
      port: 6379
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
